[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
